##### youtube:: https://www.youtube.com/watch?v=XoTwndOgXBM&t=2900s checkout this link 
##### github:: https://github.com/codeheroku/Introduction-to-Machine-Learning/tree/master/Building%20a%20Movie%20Recommendation%20Engine/.ipynb_checkpoints

In [1]:
import pandas as pd 
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
text= ['good boy good ', 'good girl boy']
list(enumerate(text))

[(0, 'good boy good '), (1, 'good girl boy')]

In [3]:
cv=CountVectorizer()

In [4]:
matrix=cv.fit_transform(text)
print(matrix.toarray())

[[1 0 2]
 [1 1 1]]


In [5]:
## find the cosine similarity 

In [6]:
score=cosine_similarity(matrix)
print(score)

[[1.         0.77459667]
 [0.77459667 1.        ]]


## now apply it on real data 

In [7]:
df=pd.read_csv('new_data.csv')
df.head()
#df.isnull().sum()

Unnamed: 0  Unnamed: 0.1      director_name     actor_1_name  \
0           0           0.0      James Cameron      CCH Pounder   
1           1           1.0     Gore Verbinski      Johnny Depp   
2           2           2.0         Sam Mendes  Christoph Waltz   
3           3           3.0  Christopher Nolan        Tom Hardy   
4           4           4.0        Doug Walker      Doug Walker   

       actor_2_name          actor_3_name                           genres  \
0  Joel David Moore             Wes Studi  Action Adventure Fantasy Sci-Fi   
1     Orlando Bloom        Jack Davenport         Action Adventure Fantasy   
2      Rory Kinnear      Stephanie Sigman        Action Adventure Thriller   
3    Christian Bale  Joseph Gordon-Levitt                  Action Thriller   
4        Rob Walker               unknown                      Documentary   

                                         movie_title  \
0                                            avatar    
1          pirates of the caribbean: at world's end    
2                                           spectre    
3                             the dark knight rises    
4  star wars: episode vii - the force awakens    ...   

                                                comb  
0  CCH Pounder Joel David Moore Wes Studi James C...  
1  Johnny Depp Orlando Bloom Jack Davenport Gore ...  
2  Christoph Waltz Rory Kinnear Stephanie Sigman ...  
3  Tom Hardy Christian Bale Joseph Gordon-Levitt ...  
4  Doug Walker Rob Walker unknown Doug Walker Doc...

In [8]:
df=df.loc[:150,['director_name', 'actor_1_name', 'actor_2_name', 'actor_3_name',
       'genres', 'movie_title', 'comb']]


In [9]:
count_matrix=cv.fit_transform(df['comb'])
print(count_matrix.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [10]:
sim_score=cosine_similarity(count_matrix)
print(sim_score)

[[1.         0.24174689 0.16116459 ... 0.29649973 0.22237479 0.0805823 ]
 [0.24174689 1.         0.18181818 ... 0.1672484  0.0836242  0.09090909]
 [0.16116459 0.18181818 1.         ... 0.3344968  0.0836242  0.18181818]
 ...
 [0.29649973 0.1672484  0.3344968  ... 1.         0.23076923 0.2508726 ]
 [0.22237479 0.0836242  0.0836242  ... 0.23076923 1.         0.0836242 ]
 [0.0805823  0.09090909 0.18181818 ... 0.2508726  0.0836242  1.        ]]


In [11]:
## if i give index i will get title 
## elseif i give title will get index

In [12]:
def get_title_from_index(i):
    return df[df.index == i]["movie_title"].values[0]
def get_index_from_title(t):
    return df[df['movie_title'] == t].index.values[0]

In [13]:
#df['movie_title'].apply(get_index_from_title)


In [14]:
movie_user_likes = "x-men: the last stand\xa0"
movie_index= get_index_from_title(movie_user_likes)
get_title_from_index(1)

"pirates of the caribbean: at world's end\xa0"

In [15]:
## enumerate return values in tuple with index,values

In [16]:
similar_movies=list(enumerate(sim_score[movie_index]))
## similar_movies

In [17]:
sorted_similar_movies = sorted(similar_movies,key=lambda x:x[1],reverse=True)
## print(sorted_similar_movies)

In [18]:
## now get the movie name from index by using upper fuction 

In [19]:
for i in sorted_similar_movies:
    print(get_title_from_index(i[0]))

x-men: the last stand 
x-men: days of future past 
x-men origins: wolverine 
transformers: age of extinction 
the amazing spider-man 2 
man of steel 
battleship 
star trek beyond 
waterworld 
mad max: fury road 
armageddon 
stealth 
avatar 
jurassic world 
world war z 
g.i. joe: the rise of cobra 
inception 
men in black 3 
men in black ii 
big hero 6 
g-force 
terminator salvation 
star trek into darkness 
terminator genisys 
the matrix reloaded 
star trek 
john carter 
batman v superman: dawn of justice 
superman returns 
transformers: revenge of the fallen 
green lantern 
transformers: dark of the moon 
rush hour 3 
2012 
jupiter ascending 
x-men: apocalypse 
edge of tomorrow 
captain america: the winter soldier 
independence day: resurgence 
guardians of the galaxy 
x-men: first class 
rise of the guardians 
avengers: age of ultron 
captain america: civil war 
iron man 3 
the mummy: tomb of the dragon emperor 
suicide squad 
dawn of the planet of the apes 
tomorrowland 
transformer

model is working pretty good 